services:
 - type: worker
   name: kerm-md-demo
   env: docker
   plan: free
   dockerfilePath: ./Dockerfile
   envVars:
    - key: SESSION_ID
      value: Session~
    - key: BOT_INFO
      value: Kɢᴛᴇᴄʜ;Kᴇʀᴍ-ʟɪᴛᴇ
    - key: SUDO
      value: 237656520674
    - key: ANTILINK
      value: "true"
