services:
 - type: worker
   name: kerm-md-demo
   env: docker
   plan: free
   dockerfilePath: ./Dockerfile
   envVars:
    - key: SESSION_ID
      value: 
    - key: BOT_INFO
      value: Kɢᴛᴇᴄʜ;༺𝐊𝐄𝐑𝐌-𝐋𝐈𝐓𝐄༻
    - key: SUDO
      value: 237656520674
    - key: ANTILINK
      value: "true"
